### ISSUE TITLE
How do we show results from a code block execution?

### ISSUE THREAD

**Issue by bnord** [deepskies/DeepWiki#11]
Should we make tables?

For example:

$ echo $HOSTNAME
$ hostname -i
$ source activate base
$ which jupyter-notebook
$ jupyter notebook --no-browser --ContentsManager.allow_hidden=True --ip={output of hostname -i} --port 8111

**Comment by samueldmcdermott** [comment]
do you want me to make a table? The alternative is to include output lines in between the lines that begin with `$`

**Comment by samueldmcdermott** [comment]
(I prefer not doing a table)
