### ISSUE TITLE
Breakdown the sinteractive text to instructions

### ISSUE THREAD

**Issue by bnord** [deepskies/DeepWiki#12]
> RCC recommends using sinteractive most of the time. To use a CPU, that takes the form of sinteractive -A kicpaa -p kicpaa but if kicpaa is your primary affiliation (rather than pinord) it might work without the flags.

**Comment by samueldmcdermott** [comment]
what does "breakdown" mean in this instance?

**Comment by samueldmcdermott** [comment]
I think Brian resolved this
