### ISSUE TITLE
make the flag list a table for clearer formatting

### ISSUE THREAD

**Issue by bnord** [deepskies/DeepWiki#15]
-v verbose
-N Do not execute a remote command. This is useful for just forwarding ports. Refer to the description of SessionType in ssh_config(5) for details. (copied and pasted from man ssh)
-f Requests ssh to go to background just before command execution. This is useful if ssh is going to ask for passwords or passphrases, but the user wants it in the background (copied and pasted from man ssh)
-L Specifies that connections to the given TCP port or Unix socket on the local (client) host are to be forwarded to the given host and port, or Unix socket, on the remote side (copied and pasted from man ssh)

**Comment by samueldmcdermott** [comment]
I kind of dislike tables. But also these commands are necessary for the functionality described, so it's not essential to describe them. We could instead delete this long list and say "use `man ssh` to see definitions of various flags". Is that ok?
