### ISSUE TITLE
Conda needed?

### ISSUE THREAD

**Issue by bnord** [deepskies/DeepWiki#19]
- [ ] if we don't need poetry, do we also not need conda? 
- [ ] or does poetry not handle environment stuff that would be needed?
- [ ] Is this where conda offers something that poetry doesn't?

**Comment by samueldmcdermott** [comment]
my current understanding is that `poetry` is for development and `conda` is for managing external libraries. So you use `poetry` on your laptop to "observe" your package and make it locally `pip` installable anywhere, but you use `conda` to install eg `camb` or `namaster`. The reasons to use `conda` are that cluster admins seem to like `conda` and virtual environments are extremely easy with it, so this allows us to have our own external libraries that aren't available by default on the cluster (eg `camb` and `namaster`) to which we can add our `pip` installable package (whose packaging was created on our local machines with `poetry`)

tagging @voetberg to make sure I didn't hash any of this explanation very badly

**Comment by voetberg** [comment]
This is all functionally correct, with some extra details. 

If people are not developing on rcc, simply making sure the package installs locally by doing `pip install <git repo>`, nothing else would be required. That would use the wheel that's already built in the repo (after you run a `poetry build`), and you don't need to worry about package management. 

You would not need to use conda to install anything as long as you can pip install things (ei, the toml for your project contains things like camb/namaster). You'd just need to run `conda activate; pip install git+<repo>` if you're required to run within a venv. If they're pushing for conda that is. (You can do the same thing in a poetry shell, but if they're gonna get mad about pip installing anything to the base env, sticking is conda makes sense.)
