### ISSUE TITLE
Where would this call take place?

### ISSUE THREAD

**Issue by bnord** [deepskies/DeepWiki#20]
> and then you would call for i in {0..5}; do sbatch <file name>.sh $i; done

- [ ] Where would this call take place?
- [ ] In what scenario would I do this?
- [ ] What's the practical result of this? i.e., we should state this would produce N runs
- [ ] Could I put this loop inside the batch file?

**Comment by samueldmcdermott** [comment]
this is bash scripting that happens in the command line interface
