### ISSUE TITLE
How to log in to a compute node from a login node?

### ISSUE THREAD

**Issue by bnord** [deepskies/DeepWiki#22]
> the most common (and easiest) way is by running sinteractive (with optional flags as described on the RCC website)

How does this work?

**Comment by samueldmcdermott** [comment]
that's described in the Usage section -- should we link to that (is there a way to link?), or just say "as described in the Usage section below"? Or remove this phrase? Any of these is good to me

**Comment by samueldmcdermott** [comment]
clarified documentation and think this is clearer now
