### ISSUE TITLE
Where and how to use sinteractive is unclear

### ISSUE THREAD

**Issue by bnord** [deepskies/DeepWiki#24]
Sinteractive is mentioned in a few places. 
Let's clarify what it means, and what is supposed to be used for. 
Think of an undegrad who has command line interface skill, but hasn't seen this command before.

**Comment by samueldmcdermott** [comment]
I can see that this might be useful, but it's also not RCC-specific, and there's plenty of general stuff we don't mention... like, we don't define `ssh` either, and we don't discuss `scp`/`rsync` at all, and I think that's fine, that's all beyond scope. This is easy to google, and we give clear guidance on the RCC-specific parts of it. I worry that bloating the content makes it harder to find useful bits

Anyway, that's my opinion, but if you think there's something special about `sinteractive` we could say a few words

**Comment by samueldmcdermott** [comment]
added some lines about using compute nodes
