### ISSUE TITLE
update gpu run instructions to be step-by-step and not narrative

### ISSUE THREAD

**Issue by bnord** [deepskies/DeepWiki#7]
This is narrative

> running with a gpu would presumably require a flag along with sinteractive, but it might be possible to invoke it from the compute node -- I'll look into this now
> 
> from sinteractive --help I see that the flag you can use for a gpu is --gres=gpu:1 (the full list of flag options is given at sbatch --help, gres is "generic resources")

But, we want there to be step-by-step things that provide instruction and an example

**Comment by samueldmcdermott** [comment]
sure -- this is also incomplete as written, since there is actually a different partition for it. So I will update the instructions for this

also -- currently this is in the login section, which I don't think is where it ought to be, so I will move it

**Comment by samueldmcdermott** [comment]
should be better now!
