### ISSUE TITLE
can one use poetry on RCC?

### ISSUE THREAD

**Issue by bnord** [deepskies/DeepWiki#8]
- [ ] can poetry be used immediately on RCC?
- [ ] can poetry be installed easily on RCC?
- [ ] How can it be installed on RCC?

**Comment by voetberg** [comment]
What's rcc in this case? 

I guess if you have access to pip, you can write a setup script (similar to the github actions that execute an install) that will execute before the code does). Good thing to have a  recipe for.

**Comment by samueldmcdermott** [comment]
RCC is the Research Computing Cluster at UChicago

but I'm thinking that development will happen not on the cluster, and we'll just use `pip install .` on RCC, so `poetry` won't be needed there

**Comment by voetberg** [comment]
Should be fine then. As long as the package has a built distribution it's completely fine. No dev -> No poetry.
